// <auto-generated />
using System;
using BasvuruTakip.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BasvuruTakip.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250521141414_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BasvuruTakip.Models.Il", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Iller");
                });

            modelBuilder.Entity("BasvuruTakip.Models.Ilce", b =>
                {
                    b.Property<long>("IlceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IlceId"));

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("IlId")
                        .HasColumnType("bigint");

                    b.HasKey("IlceId");

                    b.ToTable("Ilceler");
                });

            modelBuilder.Entity("BasvuruTakip.Models.Personel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<string>("AdiSoyadi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cinsiyet")
                        .HasColumnType("text");

                    b.Property<DateTime>("DogumTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("IlId")
                        .HasColumnType("bigint");

                    b.Property<long>("IlceId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Personeller");
                });

            modelBuilder.Entity("BasvuruTakip.Models.PersonelIsBasvurusu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<DateTime>("BasvuruTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("IlId")
                        .HasColumnType("bigint");

                    b.Property<string>("IsyeriAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("PersonelId")
                        .HasColumnType("bigint");

                    b.Property<string>("Pozisyon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("SeyahatEngeliYok")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("PersonelId");

                    b.ToTable("PersonelIsBasvurulari");
                });

            modelBuilder.Entity("BasvuruTakip.Models.PersonelIsBasvurusu", b =>
                {
                    b.HasOne("BasvuruTakip.Models.Personel", "Personel")
                        .WithMany("Basvurular")
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("BasvuruTakip.Models.Personel", b =>
                {
                    b.Navigation("Basvurular");
                });
#pragma warning restore 612, 618
        }
    }
}
