// <auto-generated />
using System;
using BasvuruTakip.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BasvuruTakip.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BasvuruTakip.Models.Il", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("adi");

                    b.HasKey("Id");

                    b.ToTable("iller");
                });

            modelBuilder.Entity("BasvuruTakip.Models.Ilce", b =>
                {
                    b.Property<long>("IlceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ilceid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IlceId"));

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("adi");

                    b.Property<long>("IlId")
                        .HasColumnType("bigint")
                        .HasColumnName("ilid");

                    b.HasKey("IlceId");

                    b.ToTable("ilceler");
                });

            modelBuilder.Entity("BasvuruTakip.Models.Personel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text")
                        .HasColumnName("aciklama");

                    b.Property<string>("AdiSoyadi")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("adisoyadi");

                    b.Property<string>("Cinsiyet")
                        .HasColumnType("text")
                        .HasColumnName("cinsiyet");

                    b.Property<DateTime>("DogumTarihi")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dogumtarihi");

                    b.Property<long>("IlId")
                        .HasColumnType("bigint")
                        .HasColumnName("ilid");

                    b.Property<long>("IlceId")
                        .HasColumnType("bigint")
                        .HasColumnName("ilceid");

                    b.HasKey("Id");

                    b.ToTable("personeller");
                });

            modelBuilder.Entity("BasvuruTakip.Models.PersonelIsBasvurusu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text")
                        .HasColumnName("aciklama");

                    b.Property<DateTime>("BasvuruTarihi")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("basvurutarihi");

                    b.Property<long>("IlId")
                        .HasColumnType("bigint")
                        .HasColumnName("ilid");

                    b.Property<string>("IsyeriAdi")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("isyeriadi");

                    b.Property<long>("PersonelId")
                        .HasColumnType("bigint")
                        .HasColumnName("personelid");

                    b.Property<string>("Pozisyon")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pozisyon");

                    b.Property<bool>("SeyahatEngeliYok")
                        .HasColumnType("boolean")
                        .HasColumnName("seyahatengeliyok");

                    b.HasKey("Id");

                    b.HasIndex("PersonelId");

                    b.ToTable("personelisbasvurulari");
                });

            modelBuilder.Entity("BasvuruTakip.Models.PersonelIsBasvurusu", b =>
                {
                    b.HasOne("BasvuruTakip.Models.Personel", "Personel")
                        .WithMany("Basvurular")
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("BasvuruTakip.Models.Personel", b =>
                {
                    b.Navigation("Basvurular");
                });
#pragma warning restore 612, 618
        }
    }
}
